FROM nginx:alpine

# Step 1: Set the working directory inside the container to /usr/src/app/Frontend
WORKDIR /usr/src/app/frontend

# Step 2: Copy the production build from the previous build stage into the Nginx server's root directory
COPY  ./src/main/resources/templates /usr/share/nginx/html

# Step 3: Expose port 80 so the app can be accessed through the Nginx server
EXPOSE 80

# Step 4: Run Nginx in the foreground to serve the React app
CMD ["nginx", "-g", "daemon off;"]